### PR TITLE
Adding filter for redirect url

### PR DESCRIPTION
**Pull request by connorjburton**
**Issue**

As far as I can see there is no way to modify the redirect URL. See the scenario described in #247 

**Solution**

Adds a filter to `ccf_form_completion_redirect_url`, aptly named `ccf_form_completion_redirect_url`. The first parameter is the the redirect value, the second parameter is the `$_REQUEST` data.

**Usage**

```php
function modify_redirect($url) {
    $remove = '/?';
    $strippedURL = str_replace($remove, '', strstr($_REQUEST['form_page'], $remove));
    parse_str($strippedURL, $parsed);
    if(isset($parsed['j'])) {
        $url .= '?j=' . $parsed['j'];
    }
    return $url;
}
add_filter('ccf_form_completion_redirect_url', 'modify_redirect', 10);
```

**Considerations**

As far as I saw, none of the filters are documented, so that's probably something that needs doing.

P.S also added `.DS_Store` to `.gitignore`

### CODE REVIEW

**Comment by connorjburton** [comment]
May be unrelated, however when I put this change on a staging server, `http://tax-recruitment.testing.pm/wp-json/ccf/v1/forms/32` wouldn't return when trying to save a form, however on local it works fine.

**Comment by tlovett1** [comment]
Hey Connor, this is super close. No need to pass $_REQUEST to the filter as it's a global.

**Comment by connorjburton** [comment]
Must have been a bit brain dead yesterday, I was sure `$_REQUEST` wasn't working. Knowing me it was most likely a typo ;)

Updated.

**Comment by tlovett1** [comment]
I'd recommend instead passing `$form_id` to the filter :)

**Comment by connorjburton** [comment]
It's like you made this plugin or something

That work? Let me know if anything else you suggest

**Comment by tlovett1** [comment]
Nice work!

**Pull request merged**
